spring:
  profiles:
    active: 'dev'
  application:
    name: springboot
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    filter:
      order: 5

server:
  port: 8080

token:
  secret: unisolution
  expireTime: 4